
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
opacity = 1
option_as_alt = "Both"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
  { key = "W", mods = "Command", action = "None" }
]

[general]
import = ["~/.config/alacritty/themes/rosepine-dawn.toml"]
