env:
  TERM: alacritty

window:
  opacity: 1
  decorations: buttonless
  dimensions:
    columns: 200
    lines: 60
  padding:
    x: 10
    y: 10
  option_as_alt: OnlyLeft

scrolling:
  history: 10000

font:
  normal:
    family: Liga SFMono Nerd Font
    style: Regular
  bold:
    family: Liga SFMono Nerd Font
    style: Bold
  italic:
    family: Liga SFMono Nerd Font
    style: Italic
  size: 16

draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/themes/nord.yml
