env:
  TERM: xterm-256color

window:
  opacity: 1
  decorations: buttonless
  dimensions:
    columns: 200
    lines: 60
  padding:
    x: 10
    y: 10

scrolling:
  history: 10000

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  size: 14

draw_bold_text_with_bright_colors: true

import:
  - ~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_night.yml
