[colors.bright]
black = "0x22536f"
red = "0xdb3976"
green = "0x5f6e29"
yellow = "0x66def9"
blue = "0x35b5ff"
magenta = "0xec30ac"
cyan = "0xfd5e3a"
white = "0xfff6e1"

[colors.primary]
background = "0x06101e"
foreground = "0xe2d9c5"

[colors.cursor]
text = "0x000000"
cursor = "0xe2d9c5"

[colors.normal]
black = "0x100807"
red = "0xfd5e3a"
green = "0xfd5e3a"
yellow = "0x35b5ff"
blue = "0x22536f"
magenta = "0xec30ac"
cyan = "0x66def9"
white = "0xf5e5c4"
