# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

gui:
  border: "single"
  showCommandLog: false
  nerdFontsVersion: "3"
  showBottomLine: false
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
os:
  edit: lazygit_edit {{filename}}
  editAtLine: lazygit_edit {{filename}} "{{line}}"
